### ISSUE TITLE
Error when try to run app 

### ISSUE THREAD

**Issue by phuongphally** [boyan01/flutter-netease-music#121]
```java
W/FlutterEnginePluginRegistry(15460): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@a73e2ba) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@848656b).
W/FlutterEnginePluginRegistry(15460): Attempted to register plugin (tech.soit.quiet.MusicPlayerUiPlugin@17bf8c8) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@848656b).
W/FlutterEnginePluginRegistry(15460): Attempted to register plugin (io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry$ShimRegistrarAggregate@1ed7086) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@848656b).
E/AndroidRuntime(15460): FATAL EXCEPTION: main
E/AndroidRuntime(15460): Process: com.mykhmersong.mobileapp, PID: 15460
E/AndroidRuntime(15460): java.lang.RuntimeException: Unable to create service tech.soit.quiet.service.MusicPlayerService: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(15460): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4114)
E/AndroidRuntime(15460): 	at android.app.ActivityThread.access$1500(ActivityThread.java:231)
E/AndroidRuntime(15460): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
E/AndroidRuntime(15460): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15460): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(15460): 	at android.app.ActivityThread.main(ActivityThread.java:7478)
E/AndroidRuntime(15460): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15460): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/AndroidRuntime(15460): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/AndroidRuntime(15460): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime(15460): 	at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
E/AndroidRuntime(15460): 	at tech.soit.quiet.MusicPlayerServicePlugin$Companion.startServiceIsolate(MusicPlayerServicePlugin.kt:83)
E/AndroidRuntime(15460): 	at tech.soit.quiet.player.MusicPlayerSessionImpl.<init>(MusicPlayerSessionImpl.kt:259)
E/AndroidRuntime(15460): 	at tech.soit.quiet.service.MusicPlayerService$playerSession$2.invoke(MusicPlayerService.kt:27)
E/AndroidRuntime(15460): 	at tech.soit.quiet.service.MusicPlayerService$playerSession$2.invoke(MusicPlayerService.kt:15)
E/AndroidRuntime(15460): 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
E/AndroidRuntime(15460): 	at tech.soit.quiet.service.MusicPlayerService.getPlayerSession(Unknown Source:2)
E/AndroidRuntime(15460): 	at tech.soit.quiet.service.MusicPlayerService.onCreate(MusicPlayerService.kt:39)
E/AndroidRuntime(15460): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4102)
```

**Comment by boyan01** [comment]
Is there a way to reproduce this problem ?
