### ISSUE TITLE
Failed to build the linux desktop version

### ISSUE THREAD

**Issue by axionl** [boyan01/flutter-netease-music#149]
## SDK: 
- Flutter 2.9.0-1.0.pre.140 • channel master • https://github.com/flutter/flutter.git
- Framework • revision d571257a99 (71 minutes ago) • 2021-12-21 02:44:10 +0100
- Engine • revision 8fabdda44d
- Tools • Dart 2.16.0 (build 2.16.0-122.0.dev) • DevTools 2.9.1

## Output:
```
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Downloading package sky_engine...                                  833ms
Downloading flutter_patched_sdk tools...                           525ms
Downloading flutter_patched_sdk_product tools...                   377ms
Downloading linux-x64 tools...                                   2,292ms
Downloading linux-x64/font-subset tools...                         162ms
Downloading linux-x64/linux-x64-flutter-gtk tools...                4.0s
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...      2,627ms
Downloading linux-x64-release/linux-x64-flutter-gtk tools...      2,506ms
Running "flutter pub get" in flutter_netease_music...            2,850ms
Launching lib/main.dart on Linux in profile mode...

flutter_netease_music/linux/flutter/ephemeral/.plugin_symlinks/dart_vlc/dartvlc/api/api.cc:41:48: warning: cannot delete expression with pointer-to-'void' type 'void *' [-Wdelete-incomplete]
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
Building Linux application...                                           
Exception: Build process failed
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:186:5)
<asynchronous suspension>
#2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:78:5)
<asynchronous suspension>
#3      LinuxDevice.buildForDevice (package:flutter_tools/src/linux/linux_device.dart:65:5)
<asynchronous suspension>
#4      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:123:7)
<asynchronous suspension>
#5      FlutterDevice.runCold (package:flutter_tools/src/resident_runner.dart:501:33)
<asynchronous suspension>
#6      ColdRunner.run (package:flutter_tools/src/run_cold.dart:71:28)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:677:26)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     main (package:flutter_tools/executable.dart:94:3)
<asynchronous suspension>
```

**Comment by boyan01** [comment]
The project files of linux is not created before.

Just added this files by #150. 

before build project, there need a vlc installed. see more:  https://github.com/alexmercerind/dart_vlc#linux

**Comment by axionl** [comment]
> The project files of linux is not created before.
> 
> Just added this files by #150.
> 
> before build project, there need a vlc installed. see more: https://github.com/alexmercerind/dart_vlc#linux

Thanks, after I installed the VLC backend, everything it's ok, except the CJK fonts are still unsupported.

**Comment by boyan01** [comment]
Yes, it's a known issue. https://github.com/flutter/flutter/issues/90951
