### ISSUE TITLE
Restart device for first time click item to play. 

### ISSUE THREAD

**Issue by phuongphally** [boyan01/flutter-netease-music#86]
I do release apk and install on real device Samsung `Galaxy S8 ` and `Galaxy S9` running android 8.0. 

Launch home with list items working well but when I try to click play item then It restart my phone. 

Because of copyright this library?

**Comment by boyan01** [comment]
restart the devices? How about debug version?

**Comment by phuongphally** [comment]
Debug version also the same problem.

**Comment by phuongphally** [comment]
After click listView then restarts the device suddenly. So sad, 

After restart I can play normally, But when 3 hours or longer when click item to play then restart the device too.

**Comment by phuongphally** [comment]
@boyan01  I found the problem. Because I'm using `flutter master  channel sdk`

**Comment by boyan01** [comment]
I try to build an artifacts  on dev channel. 
https://github.com/boyan01/flutter-netease-music/suites/388263961/artifacts/988410

 it seems that Android SystemUI crash after app popup a media notification.

```log
01-10 19:51:28.824 28878 28878 E AndroidRuntime: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v4.media.MediaMetadataCompat
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Parcel.readParcelableCreator(Parcel.java:3059)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Parcel.readParcelable(Parcel.java:2981)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Parcel.readValue(Parcel.java:2883)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Parcel.readListInternal(Parcel.java:3324)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Parcel.readArrayList(Parcel.java:2467)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Parcel.readValue(Parcel.java:2904)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Bundle.getParcelable(Bundle.java:951)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetPlaybackStateMonitor.sendCurrentState(FaceWidgetPlaybackStateMonitor.java:426)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetPlaybackStateMonitor.updateController(FaceWidgetPlaybackStateMonitor.java:409)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetPlaybackStateMonitor.onActiveSessionsChanged(FaceWidgetPlaybackStateMonitor.java:197)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetPlaybackStateMonitor.updateSessions(FaceWidgetPlaybackStateMonitor.java:314)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetPlaybackStateMonitor.start(FaceWidgetPlaybackStateMonitor.java:302)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetPlaybackStateMonitor.setOnPlaybackStateChangedListener(FaceWidgetPlaybackStateMonitor.java:129)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetMusicController.startMusicStateListening(FaceWidgetMusicController.java:485)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetMusicController.addCallback(FaceWidgetMusicController.java:226)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.music.FaceWidgetMusicPage.onAttachedToWindow(FaceWidgetMusicPage.java:396)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:21260)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3629)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5391)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5167)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.internal.widget.ViewPager.addView(ViewPager.java:1313)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5107)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.view.ViewGroup.addView(ViewGroup.java:5080)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.pages.FaceWidgetPageAdapter.instantiateItem(FaceWidgetPageAdapter.java:81)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.internal.widget.ViewPager.addNewItem(ViewPager.java:825)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.internal.widget.ViewPager.populate(ViewPager.java:1041)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.internal.widget.ViewPager.populate(ViewPager.java:907)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.internal.widget.ViewPager.setOffscreenPageLimit(ViewPager.java:687)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.FaceWidgetContainer.reissueAllPages(FaceWidgetContainer.java:1041)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.systemui.facewidget.FaceWidgetContainer$2.onUpdateFaceWidgetRemoteViews(FaceWidgetContainer.java:319)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.keyguard.KeyguardUpdateMonitor.lambda$handleFaceWidgetRemoteViews$26(KeyguardUpdateMonitor.java:2865)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.keyguard.-$$Lambda$KeyguardUpdateMonitor$asH2_qg3nXdMjtiWkB0R35Tw4nM.accept(Unknown Source:4)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.keyguard.KeyguardUpdateMonitor.dispatchCallback(KeyguardUpdateMonitor.java:8283)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.keyguard.KeyguardUpdateMonitor.handleFaceWidgetRemoteViews(KeyguardUpdateMonitor.java:2865)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.keyguard.KeyguardUpdateMonitor.access$3000(KeyguardUpdateMonitor.java:203)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.keyguard.KeyguardUpdateMonitor$3.handleMessage(KeyguardUpdateMonitor.java:842)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7762)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-10 19:51:28.824 28878 28878 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```
